#!/bin/bash
rm pipe
set -e
echo compiling...
gcc -o fb forkbombhardcore.c
echo creatingpipe...
mkfifo pipe
echo takingdata...
./fb > pipe &
echo reading...
read fbpid < pipe
echo sleeping...
sleep 10s
echo killing...
kill -INT -$fbpid
echo removingpipe...
rm pipe
echo END